import numpy as np
import matplotlib.pyplot as plt
from HDC_testing_library import bcolors, test_lookup_generate, test_encode_HDC_RFF


# test functions - maybe make library if there is many


# function tests if the statistical properties of the table
# generated by the lookup_generate function match theoretical expectations
# mode - 0/1
# nr_tests - number of tables to test
# level_of_significance - nthreshold (0,1) to reject the hypothesis that the generated table is fair
# H - height of the generated tables
# W - width of the generated tables

plt.close('all')

imgsize = 30 #Each input vector has 30 features
maxval = 256 #The input features will be mapped from 0 to 255 (8-bit)
D_HDC = 100 #HDC hypervector dimension

print("Starting lookup_generate() test...")
assert test_lookup_generate(0, 10, maxval, imgsize, D_HDC), f"{bcolors.FAIL}The lookup_generate() function has failed in mode 0{bcolors.ENDC}"
print(f"{bcolors.OKGREEN}Mode 0 successfull{bcolors.ENDC}")
assert test_lookup_generate(1, 10, maxval, maxval, D_HDC), f"{bcolors.FAIL}The lookup_generate() function has failed in mode 1{bcolors.ENDC}"
print(f"{bcolors.OKGREEN}Mode 1 successfull{bcolors.ENDC}")


print("Starting encode_HDC_RFF() test...")
assert test_encode_HDC_RFF(D_HDC, imgsize, maxval), f"{bcolors.FAIL}The encode_HDC_RFF() function has failed{bcolors.ENDC}"
print(f"{bcolors.OKGREEN}Test passed{bcolors.ENDC}")